import { CivilizationAdvances, type CivilizationAdvance } from './types';

export const civilizationAdvancesVP1: CivilizationAdvance[] = [
	{
		name: CivilizationAdvances.Cloth_Making,
		color: { orange: true },
		cost: 50,
		discountRed: 0,
		discountGreen: 5,
		discountBlue: 0,
		discountOrange: 10,
		discountYellow: 0,
		discountedByAdvance: null,
		discountedByAdvanceNumber: 0,
		victoryPoints: 1
	},
	{
		name: CivilizationAdvances.Sculpture,
		color: { blue: true },
		cost: 50,
		discountRed: 5,
		discountGreen: 10,
		discountBlue: 0,
		discountOrange: 0,
		discountYellow: 0,
		discountedByAdvance: null,
		discountedByAdvanceNumber: 0,
		victoryPoints: 1
	},
	{
		name: CivilizationAdvances.Mysticism,
		color: { blue: true, yellow: true },
		cost: 50,
		discountRed: 0,
		discountGreen: 5,
		discountBlue: 0,
		discountOrange: 0,
		discountYellow: 5,
		discountedByAdvance: null,
		discountedByAdvanceNumber: 0,
		victoryPoints: 1
	},
	{
		name: CivilizationAdvances.Urbanism,
		color: { red: true },
		cost: 50,
		discountRed: 10,
		discountGreen: 0,
		discountBlue: 5,
		discountOrange: 0,
		discountYellow: 0,
		discountedByAdvance: null,
		discountedByAdvanceNumber: 0,
		victoryPoints: 1
	},
	{
		name: CivilizationAdvances.Monarchy,
		color: { red: true },
		cost: 60,
		discountRed: 10,
		discountGreen: 0,
		discountBlue: 0,
		discountOrange: 0,
		discountYellow: 5,
		discountedByAdvance: null,
		discountedByAdvanceNumber: 0,
		victoryPoints: 1
	},
	{
		name: CivilizationAdvances.Written_Record,
		color: { red: true, green: true },
		cost: 60,
		discountRed: 5,
		discountGreen: 0,
		discountBlue: 5,
		discountOrange: 0,
		discountYellow: 0,
		discountedByAdvance: null,
		discountedByAdvanceNumber: 0,
		victoryPoints: 1
	},
	{
		name: CivilizationAdvances.Pottery,
		color: { orange: true },
		cost: 60,
		discountRed: 0,
		discountGreen: 5,
		discountBlue: 0,
		discountOrange: 10,
		discountYellow: 0,
		discountedByAdvance: null,
		discountedByAdvanceNumber: 0,
		victoryPoints: 1
	},
	{
		name: CivilizationAdvances.Masonry,
		color: { orange: true },
		cost: 60,
		discountRed: 0,
		discountGreen: 0,
		discountBlue: 5,
		discountOrange: 10,
		discountYellow: 0,
		discountedByAdvance: null,
		discountedByAdvanceNumber: 0,
		victoryPoints: 1
	},
	{
		name: CivilizationAdvances.Mythology,
		color: { yellow: true },
		cost: 60,
		discountRed: 0,
		discountGreen: 5,
		discountBlue: 0,
		discountOrange: 0,
		discountYellow: 10,
		discountedByAdvance: null,
		discountedByAdvanceNumber: 0,
		victoryPoints: 1
	},
	{
		name: CivilizationAdvances.Empiricism,
		color: { green: true },
		cost: 60,
		discountRed: 5,
		discountGreen: 5,
		discountBlue: 10,
		discountOrange: 5,
		discountYellow: 5,
		discountedByAdvance: null,
		discountedByAdvanceNumber: 0,
		victoryPoints: 1
	},
	{
		name: CivilizationAdvances.Deism,
		color: { yellow: true },
		cost: 70,
		discountRed: 0,
		discountGreen: 0,
		discountBlue: 0,
		discountOrange: 10,
		discountYellow: 5,
		discountedByAdvance: null,
		discountedByAdvanceNumber: 0,
		victoryPoints: 1
	},
	{
		name: CivilizationAdvances.Theocracy,
		color: { red: true, yellow: true },
		cost: 80,
		discountRed: 5,
		discountGreen: 0,
		discountBlue: 0,
		discountOrange: 0,
		discountYellow: 5,
		discountedByAdvance: null,
		discountedByAdvanceNumber: 0,
		victoryPoints: 1
	},
	{
		name: CivilizationAdvances.Drama_and_Poetry,
		color: { blue: true },
		cost: 80,
		discountRed: 0,
		discountGreen: 10,
		discountBlue: 0,
		discountOrange: 0,
		discountYellow: 5,
		discountedByAdvance: null,
		discountedByAdvanceNumber: 0,
		victoryPoints: 1
	},
	{
		name: CivilizationAdvances.Music,
		color: { blue: true },
		cost: 80,
		discountRed: 10,
		discountGreen: 0,
		discountBlue: 0,
		discountOrange: 0,
		discountYellow: 5,
		discountedByAdvance: null,
		discountedByAdvanceNumber: 0,
		victoryPoints: 1
	},
	{
		name: CivilizationAdvances.Astronavigation,
		color: { green: true },
		cost: 80,
		discountRed: 0,
		discountGreen: 0,
		discountBlue: 10,
		discountOrange: 0,
		discountYellow: 5,
		discountedByAdvance: null,
		discountedByAdvanceNumber: 0,
		victoryPoints: 1
	},
	{
		name: CivilizationAdvances.Coinage,
		color: { green: true },
		cost: 90,
		discountRed: 5,
		discountGreen: 0,
		discountBlue: 10,
		discountOrange: 0,
		discountYellow: 0,
		discountedByAdvance: null,
		discountedByAdvanceNumber: 0,
		victoryPoints: 1
	},
	{
		name: CivilizationAdvances.Metalworking,
		color: { orange: true },
		cost: 90,
		discountRed: 5,
		discountGreen: 0,
		discountBlue: 0,
		discountOrange: 10,
		discountYellow: 0,
		discountedByAdvance: null,
		discountedByAdvanceNumber: 0,
		victoryPoints: 1
	}
];
export const civilizationAdvancesVP3: CivilizationAdvance[] = [
	{
		name: CivilizationAdvances.Naval_Warfare,
		color: { orange: true },
		cost: 160,
		discountRed: 10,
		discountGreen: 0,
		discountBlue: 0,
		discountOrange: 5,
		discountYellow: 0,
		discountedByAdvance: CivilizationAdvances.Cloth_Making,
		discountedByAdvanceNumber: 10,
		victoryPoints: 3
	},
	{
		name: CivilizationAdvances.Architecture,
		color: { blue: true },
		cost: 140,
		discountRed: 0,
		discountGreen: 10,
		discountBlue: 5,
		discountOrange: 0,
		discountYellow: 0,
		discountedByAdvance: CivilizationAdvances.Sculpture,
		discountedByAdvanceNumber: 10,
		victoryPoints: 3
	},
	{
		name: CivilizationAdvances.Naval_Warfare,
		color: { red: true },
		cost: 160,
		discountRed: 10,
		discountGreen: 0,
		discountBlue: 0,
		discountOrange: 5,
		discountYellow: 0,
		discountedByAdvance: CivilizationAdvances.Cloth_Making,
		discountedByAdvanceNumber: 10,
		victoryPoints: 3
	},
	{
		name: CivilizationAdvances.Monument,
		color: { yellow: true, orange: true },
		cost: 180,
		discountRed: 0,
		discountGreen: 0,
		discountBlue: 0,
		discountOrange: 10,
		discountYellow: 10,
		discountedByAdvance: CivilizationAdvances.Mysticism,
		discountedByAdvanceNumber: 10,
		victoryPoints: 3
	},
	{
		name: CivilizationAdvances.Diplomacy,
		color: { blue: true },
		cost: 160,
		discountRed: 5,
		discountGreen: 10,
		discountBlue: 0,
		discountOrange: 0,
		discountYellow: 0,
		discountedByAdvance: CivilizationAdvances.Urbanism,
		discountedByAdvanceNumber: 10,
		victoryPoints: 3
	},
	{
		name: CivilizationAdvances.Law,
		color: { red: true },
		cost: 150,
		discountRed: 10,
		discountGreen: 0,
		discountBlue: 0,
		discountOrange: 0,
		discountYellow: 5,
		discountedByAdvance: CivilizationAdvances.Monarchy,
		discountedByAdvanceNumber: 10,
		victoryPoints: 3
	},
	{
		name: CivilizationAdvances.Cartography,
		color: { green: true },
		cost: 160,
		discountRed: 0,
		discountGreen: 5,
		discountBlue: 10,
		discountOrange: 0,
		discountYellow: 0,
		discountedByAdvance: CivilizationAdvances.Written_Record,
		discountedByAdvanceNumber: 10,
		victoryPoints: 3
	},
	{
		name: CivilizationAdvances.Agriculture,
		color: { orange: true },
		cost: 120,
		discountRed: 0,
		discountGreen: 0,
		discountBlue: 5,
		discountOrange: 10,
		discountYellow: 0,
		discountedByAdvance: CivilizationAdvances.Pottery,
		discountedByAdvanceNumber: 10,
		victoryPoints: 3
	},
	{
		name: CivilizationAdvances.Engineering,
		color: { orange: true, green: true },
		cost: 160,
		discountRed: 0,
		discountGreen: 0,
		discountBlue: 10,
		discountOrange: 10,
		discountYellow: 0,
		discountedByAdvance: CivilizationAdvances.Masonry,
		discountedByAdvanceNumber: 10,
		victoryPoints: 3
	},
	{
		name: CivilizationAdvances.Literacy,
		color: { red: true, blue: true },
		cost: 110,
		discountRed: 10,
		discountGreen: 10,
		discountBlue: 5,
		discountOrange: 5,
		discountYellow: 5,
		discountedByAdvance: CivilizationAdvances.Mythology,
		discountedByAdvanceNumber: 10,
		victoryPoints: 3
	},
	{
		name: CivilizationAdvances.Medicine,
		color: { green: true },
		cost: 140,
		discountRed: 0,
		discountGreen: 0,
		discountBlue: 10,
		discountOrange: 5,
		discountYellow: 0,
		discountedByAdvance: CivilizationAdvances.Empiricism,
		discountedByAdvanceNumber: 10,
		victoryPoints: 3
	},
	{
		name: CivilizationAdvances.Fundamentalism,
		color: { yellow: true },
		cost: 150,
		discountRed: 0,
		discountGreen: 5,
		discountBlue: 0,
		discountOrange: 0,
		discountYellow: 10,
		discountedByAdvance: CivilizationAdvances.Deism,
		discountedByAdvanceNumber: 10,
		victoryPoints: 3
	},
	{
		name: CivilizationAdvances.Universal_Doctrine,
		color: { yellow: true },
		cost: 160,
		discountRed: 5,
		discountGreen: 0,
		discountBlue: 0,
		discountOrange: 0,
		discountYellow: 10,
		discountedByAdvance: CivilizationAdvances.Theocracy,
		discountedByAdvanceNumber: 10,
		victoryPoints: 3
	},
	{
		name: CivilizationAdvances.Rhetoric,
		color: { blue: true },
		cost: 130,
		discountRed: 5,
		discountGreen: 10,
		discountBlue: 0,
		discountOrange: 0,
		discountYellow: 0,
		discountedByAdvance: CivilizationAdvances.Drama_and_Poetry,
		discountedByAdvanceNumber: 10,
		victoryPoints: 3
	},
	{
		name: CivilizationAdvances.Enlightenment,
		color: { yellow: true },
		cost: 160,
		discountRed: 0,
		discountGreen: 0,
		discountBlue: 0,
		discountOrange: 5,
		discountYellow: 10,
		discountedByAdvance: CivilizationAdvances.Music,
		discountedByAdvanceNumber: 10,
		victoryPoints: 3
	},
	{
		name: CivilizationAdvances.Calendar,
		color: { green: true },
		cost: 180,
		discountRed: 5,
		discountGreen: 0,
		discountBlue: 10,
		discountOrange: 0,
		discountYellow: 0,
		discountedByAdvance: CivilizationAdvances.Astronavigation,
		discountedByAdvanceNumber: 10,
		victoryPoints: 3
	},
	{
		name: CivilizationAdvances.Trade_Routes,
		color: { orange: true },
		cost: 180,
		discountRed: 0,
		discountGreen: 0,
		discountBlue: 0,
		discountOrange: 10,
		discountYellow: 5,
		discountedByAdvance: CivilizationAdvances.Coinage,
		discountedByAdvanceNumber: 10,
		victoryPoints: 3
	},
	{
		name: CivilizationAdvances.Military,
		color: { red: true },
		cost: 170,
		discountRed: 10,
		discountGreen: 0,
		discountBlue: 0,
		discountOrange: 5,
		discountYellow: 0,
		discountedByAdvance: CivilizationAdvances.Metalworking,
		discountedByAdvanceNumber: 10,
		victoryPoints: 3
	}
];
export const civilizationAdvancesVP6: CivilizationAdvance[] = [
	{
		name: CivilizationAdvances.Monotheism,
		color: { yellow: true },
		cost: 230,
		discountRed: 5,
		discountGreen: 0,
		discountBlue: 0,
		discountOrange: 0,
		discountYellow: 20,
		discountedByAdvance: CivilizationAdvances.Fundamentalism,
		discountedByAdvanceNumber: 20,
		victoryPoints: 6
	},
	{
		name: CivilizationAdvances.Mining,
		color: { orange: true },
		cost: 230,
		discountRed: 0,
		discountGreen: 0,
		discountBlue: 5,
		discountOrange: 20,
		discountYellow: 0,
		discountedByAdvance: CivilizationAdvances.Architecture,
		discountedByAdvanceNumber: 20,
		victoryPoints: 6
	},
	{
		name: CivilizationAdvances.Provincial_Empire,
		color: { red: true },
		cost: 260,
		discountRed: 20,
		discountGreen: 0,
		discountBlue: 0,
		discountOrange: 0,
		discountYellow: 5,
		discountedByAdvance: CivilizationAdvances.Diplomacy,
		discountedByAdvanceNumber: 20,
		victoryPoints: 6
	},
	{
		name: CivilizationAdvances.Diaspora,
		color: { yellow: true },
		cost: 270,
		discountRed: 0,
		discountGreen: 5,
		discountBlue: 0,
		discountOrange: 0,
		discountYellow: 20,
		discountedByAdvance: CivilizationAdvances.Naval_Warfare,
		discountedByAdvanceNumber: 20,
		victoryPoints: 6
	},
	{
		name: CivilizationAdvances.Wonder_of_the_World,
		color: { blue: true, orange: true },
		cost: 290,
		discountRed: 0,
		discountGreen: 20,
		discountBlue: 0,
		discountOrange: 20,
		discountYellow: 0,
		discountedByAdvance: CivilizationAdvances.Monument,
		discountedByAdvanceNumber: 20,
		victoryPoints: 6
	},
	{
		name: CivilizationAdvances.Cultural_Ascendancy,
		color: { blue: true },
		cost: 280,
		discountRed: 0,
		discountGreen: 20,
		discountBlue: 0,
		discountOrange: 0,
		discountYellow: 5,
		discountedByAdvance: CivilizationAdvances.Law,
		discountedByAdvanceNumber: 20,
		victoryPoints: 6
	},
	{
		name: CivilizationAdvances.Library,
		color: { green: true },
		cost: 220,
		discountRed: 0,
		discountGreen: 5,
		discountBlue: 20,
		discountOrange: 0,
		discountYellow: 0,
		discountedByAdvance: CivilizationAdvances.Cartography,
		discountedByAdvanceNumber: 20,
		victoryPoints: 6
	},
	{
		name: CivilizationAdvances.Democracy,
		color: { red: true },
		cost: 220,
		discountRed: 20,
		discountGreen: 5,
		discountBlue: 0,
		discountOrange: 0,
		discountYellow: 0,
		discountedByAdvance: CivilizationAdvances.Agriculture,
		discountedByAdvanceNumber: 20,
		victoryPoints: 6
	},
	{
		name: CivilizationAdvances.Roadbuilding,
		color: { orange: true },
		cost: 230,
		discountRed: 0,
		discountGreen: 0,
		discountBlue: 5,
		discountOrange: 20,
		discountYellow: 0,
		discountedByAdvance: CivilizationAdvances.Engineering,
		discountedByAdvanceNumber: 20,
		victoryPoints: 6
	},
	{
		name: CivilizationAdvances.Mathematics,
		color: { green: true, blue: true },
		cost: 250,
		discountRed: 10,
		discountGreen: 20,
		discountBlue: 20,
		discountOrange: 10,
		discountYellow: 10,
		discountedByAdvance: CivilizationAdvances.Literacy,
		discountedByAdvanceNumber: 20,
		victoryPoints: 6
	},
	{
		name: CivilizationAdvances.Anatomy,
		color: { green: true },
		cost: 270,
		discountRed: 0,
		discountGreen: 0,
		discountBlue: 20,
		discountOrange: 5,
		discountYellow: 0,
		discountedByAdvance: CivilizationAdvances.Medicine,
		discountedByAdvanceNumber: 20,
		victoryPoints: 6
	},

	{
		name: CivilizationAdvances.Theology,
		color: { yellow: true },
		cost: 250,
		discountRed: 0,
		discountGreen: 0,
		discountBlue: 5,
		discountOrange: 0,
		discountYellow: 20,
		discountedByAdvance: CivilizationAdvances.Universal_Doctrine,
		discountedByAdvanceNumber: 20,
		victoryPoints: 6
	},
	{
		name: CivilizationAdvances.Politics,
		color: { blue: true },
		cost: 230,
		discountRed: 0,
		discountGreen: 20,
		discountBlue: 0,
		discountOrange: 0,
		discountYellow: 5,
		discountedByAdvance: CivilizationAdvances.Rhetoric,
		discountedByAdvanceNumber: 20,
		victoryPoints: 6
	},
	{
		name: CivilizationAdvances.Philosophy,
		color: { yellow: true, green: true },
		cost: 220,
		discountRed: 0,
		discountGreen: 0,
		discountBlue: 20,
		discountOrange: 0,
		discountYellow: 20,
		discountedByAdvance: CivilizationAdvances.Enlightenment,
		discountedByAdvanceNumber: 20,
		victoryPoints: 6
	},
	{
		name: CivilizationAdvances.Public_Works,
		color: { red: true },
		cost: 230,
		discountRed: 20,
		discountGreen: 0,
		discountBlue: 0,
		discountOrange: 5,
		discountYellow: 0,
		discountedByAdvance: CivilizationAdvances.Calendar,
		discountedByAdvanceNumber: 20,
		victoryPoints: 6
	},
	{
		name: CivilizationAdvances.Trade_Empire,
		color: { orange: true },
		cost: 260,
		discountRed: 5,
		discountGreen: 0,
		discountBlue: 0,
		discountOrange: 20,
		discountYellow: 0,
		discountedByAdvance: CivilizationAdvances.Trade_Routes,
		discountedByAdvanceNumber: 20,
		victoryPoints: 6
	},
	{
		name: CivilizationAdvances.Advanced_Military,
		color: { red: true },
		cost: 240,
		discountRed: 20,
		discountGreen: 0,
		discountBlue: 5,
		discountOrange: 0,
		discountYellow: 0,
		discountedByAdvance: CivilizationAdvances.Military,
		discountedByAdvanceNumber: 20,
		victoryPoints: 6
	}
];

export const civilizationAdvances: CivilizationAdvance[] = [
	...civilizationAdvancesVP1,
	...civilizationAdvancesVP3,
	...civilizationAdvancesVP6
];
