FROM --platform=linux/arm64 node:20.12.0-alpine AS builder
WORKDIR /usr/src/app

COPY . /usr/src/app
COPY package*.json ./

RUN npm install
COPY . .
RUN npx prisma generate

EXPOSE 5555
CMD ["npx", "prisma", "studio", "--port", "5555"]

